config/routes.rb
MicroFluidics::Application.routes.draw do

  resources :design_licenses

  resources :links
    
  resources :performances do
    member do
      get :show_img
      get :download
    end  # do
  end  # do

  resources :performances

  resources :useds

  resources :papers

  resources :instrument_types

  resources :instruments
    

  resources :attachments do
    member do
      get :download
      get :show_image
      post :upload
    end  # do
  end  # do
    
  resources :attachments
    
  resources :softwares do
    member do
      get :download
    end  # do
  end  # do

  resources :softwares

  resources :members

  resources :users

  resources :teams
    
  resources :videos do
    collection do
      get :download
      get :show_video
    end  # do
  end  # do

  resources :videos

  resources :comments

  resources :designs
    
  resources :images do
    collection do
      get 'show_img'
      post 'upload'
    end  # do
  end  # do

  resources :images

  resources :deriveds

  resources :licenses

  resources :attribute_values

  resources :attributes
    
  resources :logins
    
  resources :logins do
    collection do
      get  'logout', 'logins'
      post 'verify'
    end  # do
  end  # do

  

end

app/models/design.rb
class Design < ActiveRecord::Base

# Author::    	Darrell O. Ricke, Ph.D., MIT Lincoln Laboraotry
# Copyright:: 	Copyright (c) 2014 Massachusetts Institute of Technogy 
# License::   	GNU GPL license  (http://www.gnu.org/licenses/)
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
  belongs_to :instrument
  belongs_to :team
  belongs_to :user
    
  has_many :attachment
  has_many :attribute_value
  has_many :comment
  has_many :derived
  has_many :design_license
  has_many :license, :through => :design_license
  has_many :image
  has_many :link
  has_many :paper
  has_many :performance
  has_many :software
  has_many :used
  has_many :video
    
  validates_presence_of :user_id
  validates_presence_of :design_name
  validates_presence_of :views
  validates_presence_of :downloads
  validates_presence_of :created_at
  validates_presence_of :updated_at

end  # Design

app/controllers/designs_controller.rb
#############################################################################
class DesignsController < ApplicationController
  before_action :set_design

# Author::    	Darrell O. Ricke, Ph.D., MIT Lincoln Laboraotry
# Copyright:: 	Copyright (c) 2014 Massachusetts Institute of Technogy 
# License::   	GNU GPL license  (http://www.gnu.org/licenses/)
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
#############################################################################
  # GET /designs
  # GET /designs.json
  def index
    @teams = Team.all
    @teams_hash = Tools.to_hash(@teams)
    @users = User.all
    @users_hash = Tools.to_hash(@users)
    @instruments = Instrument.all
    @instruments_hash = Tools.to_hash(@instruments)
    @designs = Design.all
    session[:design_id] = nil
    session[:is_owner] = nil
    session[:team_id] = nil
  end  # index

#############################################################################
  # GET /designs/1
  # GET /designs/1.json
  def show
    @design.views += 1  # Update the number of views
    @design.save
      
    @users = User.all
    @users_hash = Tools.to_hash(@users)
    @images = Image.find_all_by_design_id(@design.id)
    @licenses = License.all
    @licenses_hash = Tools.to_hash(@licenses)
    @design_licenses = DesignLicense.find_all_by_design_id(@design.id)
    @comments = Comment.find_all_by_design_id(@design.id)
    @comments_hash = Tools.to_hash(@comments)
    @team = nil
    @team = Team.find(@design.team_id) if ! @design.team_id.nil?
    @instrument = Instrument.find(@design.instrument_id)
    @papers = Paper.find_all_by_design_id(@design.id)
    @performances = Performance.find_all_by_design_id(@design.id)
    @softwares = Software.find_all_by_design_id(@design.id)
    @attachments = Attachment.find_all_by_design_id(@design.id)
    @videos = Video.find_all_by_design_id(@design.id)
    @useds = Used.find_all_by_design_id(@design.id)
    @deriveds = Derived.find_all_by_design_id(@design.id)
    @attributes = Attribute.all
    @attributes_hash = Tools.to_hash(@attributes)
    @attribute_values = AttributeValue.find_all_by_design_id(@design.id)
    session[:design_id] = @design.id
    session[:team_id] = @design.team_id
  end  # show

#############################################################################
  # GET /designs/new
  def new
    @design = Design.new
  end  # new

#############################################################################
  # GET /designs/1/edit
  def edit
  end  # edit

#############################################################################
  # POST /designs
  # POST /designs.json
  def create
    @design = Design.new(design_params)
    @design.user_id = session[:user_id]
    @design.views = 0
    @design.downloads = 0
    @design.created_at = Time::now
    @design.updated_at = Time::now

    respond_to do |format|
      if @design.save
        format.html { redirect_to @design, notice: 'Design was successfully created.' }
        format.json { render action: 'show', status: :created, location: @design }
      else
        format.html { render action: 'new' }
        format.json { render json: @design.errors, status: :unprocessable_entity }
      end  # if
    end  # do
  end  # create

#############################################################################
  # PATCH/PUT /designs/1
  # PATCH/PUT /designs/1.json
  def update
    #  @design.updated_at = Time::now
    respond_to do |format|
      if @design.update(design_params)
        format.html { redirect_to @design, notice: 'Design was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @design.errors, status: :unprocessable_entity }
      end  # if
    end  # do
  end  # update

#############################################################################
  # DELETE /designs/1
  # DELETE /designs/1.json
  def destroy
    if session[:is_owner]
      @design.destroy
      respond_to do |format|
        format.html { redirect_to designs_url }
        format.json { head :no_content }
      end  # do
    end # if
  end  # destroy

  private
#############################################################################
    # Use callbacks to share common setup or constraints between actions.
    def set_design
      @users = User.all
      @users_hash = Tools.to_hash(@users)
      @instruments = Instrument.all
      @instruments_hash = Tools.to_hash(@instruments)
      @designs = Design.all
      @design = Design.find(params[:id]) if ! params[:id].nil?
      @teams = Team.all
      @teams_hash = Tools.to_hash(@teams)
      @members = Member.find_all_by_user_id(session[:user_id]) if ! session[:user_id].nil? 
      session[:is_owner] = (session[:user_id] == @design.user_id) if ! @design.nil?
      session[:is_owner] = true if session[:is_admin]
    end  # set_design

#############################################################################
    # Never trust parameters from the scary internet, only allow the white list through.
    def design_params
      params.require(:design).permit(:user_id, :team_id, :instrument_id, :design_name, :revision, :rating, :views, :downloads, :created_at, :updated_at)
    end  # design_params
    #############################################################################
end  # class

app/helpers/designs_helper.rb
module DesignsHelper
end

app/views/designs/_form.html.erb
<%= form_for(@design) do |f| %>
  <% if @design.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@design.errors.count, "error") %> prohibited this design from being saved:</h2>

      <ul>
      <% @design.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <table>
    <thead></thead>
    <tbody>
      <tr>
  <div class="field">
    <td><%= f.label :team_id %></td>
    <td><%= f.collection_select(:team_id, @teams, :id, :team_name, {:include_blank => "No team"}) %></td>
  </div>
      </tr><tr>
  <div class="field">
    <td><%= f.label :instrument_id %></td>
    <td><%= f.collection_select(:instrument_id, @instruments, :id, :instrument_name) %></td>
  </div>
      </tr><tr>
  <div class="field">
    <td><%= f.label :design_name %></td>
    <td><%= f.text_field :design_name, :size => 80 %></td>
  </div>
      </tr><tr>
  <div class="field">
    <td><%= f.label :revision %></td>
    <td><%= f.text_field :revision %></td>
  </div>
      </tr>
    </tbody>
  </table>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/designs/edit.html.erb
<h1>Editing Design</h1>

<%= render 'form' %>

<%= link_to 'Show', @design %> |
<%= link_to 'Back', designs_path %>

app/views/designs/index.html.erb
<h1>Designs</h1>

<table cellpadding="2" class="display dataTable" id="example">
  <thead>
    <tr>
      <th>User</th>
      <th>Team</th>
      <th>Instrument</th>
      <th>Design name</th>
      <th>Revision</th>
      <th>Rating</th>
      <th>Views</th>
      <th>Downloads</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th></th>
      <% if session[:user_id] -%>
        <th></th>
        <th></th>
      <% end -%>
    </tr>
  </thead>

  <tbody>
    <% @designs.each do |design| %>
      <tr align="center">
        <td><%= @users_hash[design.user_id].name if ! @users_hash[design.user_id].nil? %></td>
        <td><%= @teams_hash[design.team_id].team_name if ! @teams_hash[design.team_id].nil? %></td>
        <td><%= @instruments_hash[design.instrument_id].instrument_name if ! @instruments_hash[design.instrument_id].nil? %></td>
        <td><%= design.design_name %></td>
        <td><%= design.revision %></td>
        <td><%= design.rating %></td>
        <td><%= design.views %></td>
        <td><%= design.downloads %></td>
        <td><%= Tools.to_ampm(design.created_at) %></td>
        <td><%= Tools.to_ampm(design.updated_at) %></td>
        <td><%= link_to 'Show', design %></td>
        <% if session[:user_id] -%>
          <% if design.user_id == session[:user_id] -%>
            <td><%= link_to 'Edit', edit_design_path(design) %></td>
            <td><%= link_to 'Destroy', design, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% else -%>
            <td></td>
            <td></td>
          <% end -%>
        <% end -%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Design', new_design_path if (! session[:user_id].nil?) %>

app/views/designs/new.html.erb
<h1>New design</h1>

<%= render 'form' %>

<%= link_to 'Back', designs_path %>

app/views/designs/show.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead></thead>
  <tbody>
<tr>
  <td><strong>User:</strong></td>
  <td><%= @users_hash[@design.user_id].name if ! @users_hash[@design.user_id].nil? %></td>
</tr><tr>
  <td><strong>Team:</strong></td>
  <td><%= @team.team_name if ! @team.nil? %></td>
</tr><tr>
  <td><strong>Instrument:</strong></td>
  <td><%= @instrument.instrument_name if ! @instrument.nil? %></td>
</tr><tr>
  <td><strong>Design name:</strong></td>
  <td><%= @design.design_name %></td>
</tr><tr>
  <td><strong>Revision:</strong></td>
  <td><%= @design.revision %></td>
</tr><tr>
  <td><strong>Rating:</strong></td>
  <td><%= @design.rating %></td>
</tr><tr>
  <td><strong>Views:</strong></td>
  <td><%= @design.views %></td>
</tr><tr>
  <td><strong>Downloads:</strong></td>
  <td><%= @design.downloads %></td>
</tr><tr>
  <td><strong>Created at:</strong></td>
  <td><%= Tools.to_ampm(@design.created_at) %></td>
</tr><tr>
  <td><strong>Updated at:</strong></td>
  <td><%= Tools.to_ampm(@design.updated_at) %></td>
</tr>
</tbody>
</table>
<br />
<strong>Licenses</strong>
<br />
<% if @design_licenses.length > 0 -%>
  <table cellpadding="0" border="0" class="display dataTable" id="example">
    <thead>
      <tr>
        <th>License</th>
        <th>Version</th>
        <th>URL</th>
        <% if @owns -%>
          <th></th>
        <% end -%>
      </tr>
    </thead>
    <tbody>
    <% @design_licenses.each do |design_license| -%>
      <% license = @licenses_hash[design_license.license_id] -%>
      <% if ! license.nil? -%>
        <tr>
          <td><%= license.license_name %></td>
          <td align="center"><%= license.license_version %></td>
          <td><%= license.license_url %></td>
          <% if @owns -%>
            <td><%= link_to 'Remove', design_license, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end -%>
        </tr>
      <% end -%>
    <% end -%>
    </tbody>
  </table>
<% end -%>
<%= link_to 'Add a license', new_design_license_path if @owns %>
<br /><br />

<strong>Images</strong>
<br />
<% if @images.length > 0 -%>
  <table cellpadding="0" border="0" class="display dataTable" id="example">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Thumbnail</th>
        <th>See Image</th>
        <% if @owns -%>
          <th></th>
        <% end -%>
      </tr>
    </thead>
    <tbody>
   <% @images.each do |image| -%>
     <tr>
       <td><%= image.image_name %></td>
        <td><%= image.description %></td>
        <td><%= image_tag(url_for(:controller => :images, :action => :show_img, :id => image.id), :ISMAP => 'false', :border => '0', :height => '100', :width => '100') %></td>
        <td><%= link_to 'Show', image_path(image) %></td>
        <% if @owns -%>
          <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end -%>
     </tr>
  <% end -%>
    </tbody>
  </table>
<% end -%>
<%= link_to 'Add an image', new_image_path if @owns %>
<br /><br />

<strong>Videos</strong>
<br />
<% if @videos.length > 0 -%>
  <table cellpadding="0" border="0" class="display dataTable" id="example">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Category</th>
      </tr>
    </thead>
    <tbody>
  <% @videos.each do |video| -%>
    <tr>
      <td><%= video.video_name %></td>
      <td><%= video.video_description %></td>
      <td><%= video.video_category %></td>
    </tr>
  <% end -%>
    </tbody>
  </table>
<% end -%>
<%= link_to 'Add a Video', new_video_path if @owns %>
<br /><br />

<strong>Publications</strong><br />
<% if @papers.length > 0 -%>
<table cellpadding="0" cellspacing="0" border="0" class="display dataTable" id="example">
  <thead>
    <tr>
      <th>Authors</th>
      <th>Title</th>
      <th>Reference</th>
      <th>URL</th>
      <% if @owns -%>
        <th></th>
        <th></th>
      <% end -%>
    </tr>
  </thead>
  <tbody>
    <% @papers.each do |paper| %>
      <tr>
        <td><%= paper.authors %></td>
        <td><%= paper.title %></td>
        <td><%= paper.reference %></td>
        <td><%= paper.url %></td>
        <% if @owns -%>
          <td><%= link_to 'Edit', edit_paper_path(paper) %></td>
          <td><%= link_to 'Destroy', paper, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end -%>
      </tr>
    <% end %>
  </tbody>
</table>
<% end -%>
<%= link_to 'Add a reference', new_paper_path if @owns %>
<br /><br />

<strong>Performance</strong>
<br />
<% if @performances.length > 0 -%>
<table cellpadding="0" cellspacing="0" border="0" class="display dataTable" id="example">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Metric</th>
      <th>Rating</th>
      <th>Date</th>
      <th>Image</th>
      <% if @owns -%>
        <th></th>
        <th></th>
      <% end -%>
    </tr>
  </thead>

  <tbody>
    <% @performances.each do |performance| %>
      <tr>
        <td><%= performance.name %></td>
        <td><%= performance.description %></td>
        <td align="center"><%= performance.metric %></td>
        <td align="center"><%= performance.rating %></td>
        <td><%= performance.updated_at %></td>
        <td><%= link_to image_tag(url_for(:controller => :attachments, :action => :show_img, :id => performance.attachment_id), :ISMAP => 'false', :border => '0', :height => '100', :width => '100') if ! performance.attachment_id.nil? %></td>
        <% if @owns -%>
          <td><%= link_to 'Edit', edit_performance_path(performance) %></td>
          <td><%= link_to 'Destroy', performance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end -%>
      </tr>
    <% end %>
  </tbody>
</table>
<% end -%>
<%= link_to 'Add Performance Data', new_performance_path if @owns %>
<br /><br />

<strong>Software</strong>
<br />
<% if @softwares.length > 0 -%>
    <% @softwares.each do |software| %>
      <table>
        <thead></thead>
        <tbody>
          <tr>
            <td><%= software.software_name %></td>
            <td><%= software.description %></td>
            <% if @owns -%>
              <td><%= link_to 'Edit', edit_software_path(software) %></td>
              <td><%= link_to 'Destroy', software, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end -%>
          </tr>
        </tbody>
      </table>
      <pre><%= software.attachment.view if ! software.attachment_id.nil? %></pre>
    <% end -%>
<% end -%>
<%= link_to 'Add new Software', new_software_path if @owns %>
<br /><br />

<strong>People who have used this Design</strong>
<br />
<% if @useds.length > 0 -%>
<table cellpadding="0" border="0" class="display dataTable" id="example">
  <thead>
    <tr>
      <th>User</th>
      <th>Date</th>
      <th>Notes</th>
    </tr>
  </thead>
  <tbody>
    <% @useds.each do |one_use| -%>
    <tr>
      <td><%= @users_hash[one_use.user_id].name if ! @users_hash[one_use.user_id].nil? %></td>
      <td><%= Tools.to_ampm(one_use.created_at) %></td>
      <td><%= one_use.notes.html_safe if (! one_use.notes.nil?) %></td>
      <% if @owns -%>
        <td><%= link_to 'Edit', edit_used_path(one_use) %></td>
        <td><%= link_to 'Remove', one_use, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end -%>
    </tr>
    <% end -%>
  </tbody>
</table>
<% end -%>
<%= link_to 'Add a new use of this Design', new_used_path if ! session[:user_id].nil? %>
<br /><br />

<strong>Comments</strong>
<br />
<% if @comments.length > 0 -%>
<table cellpadding="0" border="0" class="display dataTable" id="example">
  <thead>
    <tr>
      <th>User</th>
      <th>Rating</th>
      <th>Date</th>
      <th>Comments</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @comments.each do |comment| -%>
        <tr>
          <td><%= @users_hash[comment.user_id].name if ! @users_hash[comment.user_id].nil? %></td>
          <td align="center"><%= comment.rating %></td>
          <td><%= Tools.to_ampm(comment.updated_at) %></td>
          <td><%= comment.comments.html_safe %></td>
          <td><%= link_to 'Remove', comment, method: :delete, data: { confirm: 'Are you sure?' } if (comment.user_id == session[:user_id]) %></td>
        </tr>
      <% end -%>
  </tbody>
</table>
<% end -%>
<%= link_to 'Add your comment', new_comment_path if ! session[:user_id].nil? %>
<br /><br />


<br />
<%= link_to 'Edit', edit_design_path(@design) if @owns %><br />
<%= link_to 'Back', designs_path %>