config/routes.rb
MicroFluidics::Application.routes.draw do

  resources :design_licenses

  resources :links
    
  resources :performances do
    member do
      get :show_img
      get :download
    end  # do
  end  # do

  resources :performances

  resources :useds

  resources :papers

  resources :instrument_types

  resources :instruments
    

  resources :attachments do
    member do
      get :download
      get :show_image
      post :upload
    end  # do
  end  # do
    
  resources :attachments
    
  resources :softwares do
    member do
      get :download
    end  # do
  end  # do

  resources :softwares

  resources :members

  resources :users

  resources :teams
    
  resources :videos do
    collection do
      get :download
      get :show_video
    end  # do
  end  # do

  resources :videos

  resources :comments

  resources :designs
    
  resources :images do
    collection do
      get 'show_img'
      post 'upload'
    end  # do
  end  # do

  resources :images

  resources :deriveds

  resources :licenses

  resources :attribute_values

  resources :attributes
    
  resources :logins
    
  resources :logins do
    collection do
      get  'logout', 'logins'
      post 'verify'
    end  # do
  end  # do

  

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base

# Author::    	Darrell O. Ricke, Ph.D., MIT Lincoln Laboraotry
# Copyright:: 	Copyright (c) 2014 Massachusetts Institute of Technogy 
# License::   	GNU GPL license  (http://www.gnu.org/licenses/)
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
  belongs_to :design
  
  has_one :attachment
  has_one :performance
    
  # validates_presence_of :file_name  # old style
  validates :file_name, {:presence => true}
  
####################################################################################################
def datafile=(input_data)
  datafile(input_data)
end  # datafile=

####################################################################################################
def datafile(input_data)
    return nil if input_data == "" #no file name was entered
    # self.file_name = base_part_of(input_data.original_filename)
    self.file_name = input_data.original_filename
    self.path_name = input_data.original_filename
    self.content_type = input_data.content_type.chomp
    self.contents = input_data.read
    self.view = self.contents
end  # datafile
    
####################################################################################################
def base_part_of(file_name)
    File.basename(file_name).gsub(/[^\w._-]/, '')
end  # base_part_of
    
####################################################################################################
end  # Attachment

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :set_attachment, only: [:show, :edit, :update, :destroy, :download, :show_img]

# Author::    	Darrell O. Ricke, Ph.D., MIT Lincoln Laboraotry
# Copyright:: 	Copyright (c) 2014 Massachusetts Institute of Technogy 
# License::   	GNU GPL license  (http://www.gnu.org/licenses/)
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
#############################################################################
  # GET /attachments
  # GET /attachments.json
  def index
    @attachments = Attachment.all
    @designs = Design.all
    @designs_hash = Tools::to_hash(@designs)
  end  # index
    
#############################################################################
  # GET /attachments/1
  # GET /attachments/1.json
  def show
    @designs = Design.all
  end  # show

#############################################################################
  # GET /attachments/new
  def new
    @attachment = Attachment.new
    @designs = Design.all
  end  # new

#############################################################################
  # GET /attachments/1/edit
  def edit
    @designs = Design.all
  end  # edit

#############################################################################
  # POST /attachments
  # POST /attachments.json
  def create
    @attachment = Attachment.new(attachment_params)
    @attachment.design_id = session[:design_id]
    @attachment.updated_at = Time::now

    respond_to do |format|
      if @attachment.save
        format.html { redirect_to design_path(session[:design_id]), notice: 'File added.' }
        format.json { render action: 'show', status: :created, location: @attachment }
      else
        @designs = Design.all
        format.html { render action: 'new' }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end  # if
    end  # do
  end  # create

#############################################################################
  # PATCH/PUT /attachments/1
  # PATCH/PUT /attachments/1.json
  def update
    respond_to do |format|
      if @attachment.update(attachment_params)
        @attachment.updated_at = Time::now
        @attachment.save
        format.html { redirect_to @attachment, notice: 'Attachment was successfully updated.' }
        format.json { head :no_content }
      else
        @designs = Design.all
        format.html { render action: 'edit' }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end  # if
    end  # do
  end  # update

#############################################################################
  # DELETE /attachments/1
  # DELETE /attachments/1.json
  def destroy
    @attachment.destroyif session[:is_owner]
    respond_to do |format|
      format.html { redirect_to designs_path(session[:design_id]) }
      format.json { head :no_content }
    end  # do
  end  # destroy
    
#############################################################################
  def download
    puts ">>>>> download called <<<<<<"
    send_data @attachment.contents, :filename => @attachment.file_name, :type => @attachment.content_type
  end  # download
    
#############################################################################
  def show_img
    send_data(@attachment.contents, :type => @attachment.content_type, :disposition => 'inline')
  end  # show_img

#############################################################################
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attachment
      @attachment = Attachment.find(params[:id])
      @owns = true if session[:is_admin]
    end  # set_attachment

#############################################################################
    # Never trust parameters from the scary internet, only allow the white list through.
    def attachment_params
        params.require(:attachment).permit(:design_id, :file_name, :path_name, :description, :file_type, :downloads, :content_type, :updated_at, :contents_bytes, :contents, :view_bytes, :view, :datafile, :save)
    end  # attachment_params
end  # class

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/views/attachments/_form.html.erb
<%= form_for(@attachment, :html => {:multipart=>true}) do |f| %>
  <% if @attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attachment.errors.count, "error") %> prohibited this attachment from being saved:</h2>

      <ul>
      <% @attachment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :design_id %><br>
    <%= f.collection_select(:design_id, @designs, :id, :design_name) %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :file %><br>
    <%= f.file_field("datafile") %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end -%>

app/views/attachments/edit.html.erb
<h1>Editing attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @attachment %> |
<%= link_to 'Back', attachments_path %>

app/views/attachments/index.html.erb
<h1>Files</h1>

<!-- table cellpadding="0" cellspacing="0" border="0" class="display dataTable" id="example" -->
<table cellpadding="2" cellspacing="0" border="0" class="display dataTable" id="example">
  <thead>
    <tr>
      <th>File name</th>
      <th>Description</th>
      <th>Downloads</th>
      <th>Updated at</th>
      <th></th>
      <th></th>
      <% if session[:is_owner] -%>
        <th></th>
        <th></th>
      <% end -%>
    </tr>
  </thead>

  <tbody>
    <% @attachments.each do |attachment| %>
      <tr>
        <td><%= attachment.file_name %></td>
        <td><%= attachment.description %></td>
        <td align="center"><%= attachment.downloads %></td>
        <td><%= attachment.updated_at %></td>
        <td><%= link_to 'Show', attachment %></td>
        <td><%= link_to 'Download', :id => attachment.id, :method => :download, :action => :download %></td>
        <% if session[:is_owner] -%>
          <td><%= link_to 'Edit', edit_attachment_path(attachment) %></td>
          <td><%= link_to 'Destroy', attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end -%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attachment', new_attachment_path if (! session[:design_id].nil?) && (! session[:user_id].nil?) %>

app/views/attachments/new.html.erb
<h1>New attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', attachments_path %>

app/views/attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Design:</strong>
  <%= @attachment.design_id %>
</p>

<p>
  <strong>File name:</strong>
  <%= @attachment.file_name %>
</p>

<p>
  <strong>Path name:</strong>
  <%= @attachment.path_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @attachment.description %>
</p>

<p>
  <strong>File type:</strong>
  <%= @attachment.file_type %>
</p>

<p>
  <strong>Downloads:</strong>
  <%= @attachment.downloads %>
</p>

<p>
  <strong>Content type:</strong>
  <%= @attachment.content_type %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @attachment.updated_at %>
</p>


<%= link_to 'Edit', edit_attachment_path(@attachment) %> |
<%= link_to 'Back', attachments_path %>