config/routes.rb
MicroFluidics::Application.routes.draw do

  resources :design_licenses

  resources :links
    
  resources :performances do
    member do
      get :show_img
      get :download
    end  # do
  end  # do

  resources :performances

  resources :useds

  resources :papers

  resources :instrument_types

  resources :instruments
    

  resources :attachments do
    member do
      get :download
      get :show_image
      post :upload
    end  # do
  end  # do
    
  resources :attachments
    
  resources :softwares do
    member do
      get :download
    end  # do
  end  # do

  resources :softwares

  resources :members

  resources :users

  resources :teams
    
  resources :videos do
    collection do
      get :download
      get :show_video
    end  # do
  end  # do

  resources :videos

  resources :comments

  resources :designs
    
  resources :images do
    collection do
      get 'show_img'
      post 'upload'
    end  # do
  end  # do

  resources :images

  resources :deriveds

  resources :licenses

  resources :attribute_values

  resources :attributes
    
  resources :logins
    
  resources :logins do
    collection do
      get  'logout', 'logins'
      post 'verify'
    end  # do
  end  # do

  

end

app/models/paper.rb
class Paper < ActiveRecord::Base
 
# Author::    	Darrell O. Ricke, Ph.D., MIT Lincoln Laboraotry
# Copyright:: 	Copyright (c) 2014 Massachusetts Institute of Technogy 
# License::   	GNU GPL license  (http://www.gnu.org/licenses/)
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
  belongs_to :design
    
  validates_presence_of :design_id
  validates_presence_of :authors
  validates_presence_of :title
  validates_presence_of :reference

end  # Paper

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  before_action :set_paper, only: [:show, :edit, :update, :destroy]

# Author::    	Darrell O. Ricke, Ph.D., MIT Lincoln Laboraotry
# Copyright:: 	Copyright (c) 2014 Massachusetts Institute of Technogy 
# License::   	GNU GPL license  (http://www.gnu.org/licenses/)
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
  # GET /papers
  # GET /papers.json
  def index
    @papers = Paper.find_all_by_design_id(session[:design_id])
  end  # index

  # GET /papers/1
  # GET /papers/1.json
  def show
  end

  # GET /papers/new
  def new
    @paper = Paper.new
  end

  # GET /papers/1/edit
  def edit
  end

  # POST /papers
  # POST /papers.json
  def create
    @paper = Paper.new(paper_params)
    @paper.design_id = session[:design_id]

    respond_to do |format|
      if @paper.save
        format.html { redirect_to design_path(session[:design_id]), notice: 'Paper was successfully created.' }
        format.json { render action: 'show', status: :created, location: @paper }
      else
        format.html { render action: 'new' }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /papers/1
  # PATCH/PUT /papers/1.json
  def update
    respond_to do |format|
      if @paper.update(paper_params)
        format.html { redirect_to @paper, notice: 'Paper was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /papers/1
  # DELETE /papers/1.json
  def destroy
    @paper.destroy if session[:is_owner]
    respond_to do |format|
      format.html { redirect_to design_path(session[:design_id]) }
      format.json { head :no_content }
    end  # do
  end  # if

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paper
      @paper = Paper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paper_params
      params.require(:paper).permit(:design_id, :url, :authors, :title, :reference)
    end
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/views/papers/_form.html.erb
<%= form_for(@paper) do |f| %>
  <% if @paper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paper.errors.count, "error") %> prohibited this paper from being saved:</h2>

      <ul>
      <% @paper.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <thead></thead>
    <tbody>
      <tr>
  <div class="field">
    <td><%= f.label :title %></td>
    <td><%= f.text_field :title, :size => 80 %></td>
  </div>
      </tr><tr>
  <div class="field">
    <td><%= f.label :authors %></td>
    <td><%= f.text_field :authors, :size => 80 %></td>
  </div>
      </tr><tr>
  <div class="field">
    <td><%= f.label :reference %></td>
    <td><%= f.text_field :reference, :size => 80 %></td>
  </div>
      </tr><tr>
  <div class="field">
    <td><%= f.label :url %></td>
    <td><%= f.text_field :url, :size => 80 %></td>
  </div>
      </tr>
    </tbody>
  </table>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/papers/edit.html.erb
<h1>Editing paper</h1>

<%= render 'form' %>

<%= link_to 'Show', @paper %> |
<%= link_to 'Back', papers_path %>

app/views/papers/index.html.erb
<h1>Papers</h1>

<table cellpadding="2" cellspacing="0" border="0" class="display dataTable" id="example">
  <thead>
    <tr>
      <th>Design</th>
      <th>Link</th>
      <th>Authors</th>
      <th>Title</th>
      <th>Reference</th>
      <th></th>
      <% if session[:is_owner] -%>
        <th></th>
        <th></th>
      <% end -%>
    </tr>
  </thead>

  <tbody>
    <% @papers.each do |paper| %>
      <tr>
        <td><%= paper.design_id %></td>
        <td><%= paper.link_id %></td>
        <td><%= paper.authors %></td>
        <td><%= paper.title %></td>
        <td><%= paper.reference %></td>
        <td><%= link_to 'Show', paper %></td>
        <% if session[:is_owner] -%>
          <td><%= link_to 'Edit', edit_paper_path(paper) %></td>
          <td><%= link_to 'Destroy', paper, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end -%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paper', new_paper_path if (! session[:design_id].nil?) && (! session[:user_id].nil?) %>

app/views/papers/new.html.erb
<h1>New paper</h1>

<%= render 'form' %>

<%= link_to 'Back', papers_path %>

app/views/papers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Design:</strong>
  <%= @paper.design_id %>
</p>

<p>
  <strong>Link:</strong>
  <%= @paper.link_id %>
</p>

<p>
  <strong>Authors:</strong>
  <%= @paper.authors %>
</p>

<p>
  <strong>Title:</strong>
  <%= @paper.title %>
</p>

<p>
  <strong>Reference:</strong>
  <%= @paper.reference %>
</p>

<%= link_to 'Edit', edit_paper_path(@paper) %> |
<%= link_to 'Back', papers_path %>