config/routes.rb
MicroFluidics::Application.routes.draw do

  resources :design_licenses

  resources :links
    
  resources :performances do
    member do
      get :show_img
      get :download
    end  # do
  end  # do

  resources :performances

  resources :useds

  resources :papers

  resources :instrument_types

  resources :instruments
    

  resources :attachments do
    member do
      get :download
      get :show_image
      post :upload
    end  # do
  end  # do
    
  resources :attachments
    
  resources :softwares do
    member do
      get :download
    end  # do
  end  # do

  resources :softwares

  resources :members

  resources :users

  resources :teams
    
  resources :videos do
    collection do
      get :download
      get :show_video
    end  # do
  end  # do

  resources :videos

  resources :comments

  resources :designs
    
  resources :images do
    collection do
      get 'show_img'
      post 'upload'
    end  # do
  end  # do

  resources :images

  resources :deriveds

  resources :licenses

  resources :attribute_values

  resources :attributes
    
  resources :logins
    
  resources :logins do
    collection do
      get  'logout', 'logins'
      post 'verify'
    end  # do
  end  # do

  

end

app/models/instrument.rb
class Instrument < ActiveRecord::Base
    
# Author::    	Darrell O. Ricke, Ph.D., MIT Lincoln Laboraotry
# Copyright:: 	Copyright (c) 2014 Massachusetts Institute of Technogy 
# License::   	GNU GPL license  (http://www.gnu.org/licenses/)
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
  validates_presence_of :instrument_type_id
  validates_presence_of :instrument_name
    
####################################################################################################
  def datafile=(input_data)
    return nil if input_data == "" #no file name was entered
    image = Image.new
    image.image_name = input_data.original_filename
    image.image_type = input_data.content_type.chomp
    image.image_use = 'Instrument'
    image.picture = input_data.read
    # self.picture_byte = self.picture.size
    image.save
    self.image_id = image.id
  end  # datafile=
    
####################################################################################################
end  # Instrument

app/models/instrument_type.rb
class InstrumentType < ActiveRecord::Base
    
# Author::    	Darrell O. Ricke, Ph.D., MIT Lincoln Laboraotry
# Copyright:: 	Copyright (c) 2014 Massachusetts Institute of Technogy 
# License::   	GNU GPL license  (http://www.gnu.org/licenses/)
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
  validates_presence_of :category

end  # InstrumentType

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  before_action :set_instrument, only: [:show, :edit, :update, :destroy]

# Author::    	Darrell O. Ricke, Ph.D., MIT Lincoln Laboraotry
# Copyright:: 	Copyright (c) 2014 Massachusetts Institute of Technogy 
# License::   	GNU GPL license  (http://www.gnu.org/licenses/)
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
  def get_refs
    @instrument_types = InstrumentType.all
    @instrument_types_hash = Tools.to_hash(@instrument_types)
    session[:is_owner] = nil
    session[:design_id] = nil
  end  # get_refs

  # GET /instruments
  # GET /instruments.json
  def index
    @instruments = Instrument.all
    get_refs
  end  # index

  # GET /instruments/1
  # GET /instruments/1.json
  def show
    get_refs
  end

  # GET /instruments/new
  def new
    @instrument = Instrument.new
    get_refs
  end

  # GET /instruments/1/edit
  def edit
    get_refs
  end

  # POST /instruments
  # POST /instruments.json
  def create
    @instrument = Instrument.new(instrument_params)

    respond_to do |format|
      if @instrument.save
        format.html { redirect_to @instrument, notice: 'Instrument was successfully created.' }
        format.json { render action: 'show', status: :created, location: @instrument }
      else
        get_refs
        format.html { render action: 'new' }
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instruments/1
  # PATCH/PUT /instruments/1.json
  def update
    respond_to do |format|
      if @instrument.update(instrument_params)
        format.html { redirect_to @instrument, notice: 'Instrument was successfully updated.' }
        format.json { head :no_content }
      else
        get_refs
        format.html { render action: 'edit' }
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instruments/1
  # DELETE /instruments/1.json
  def destroy
    @instrument.destroy if session[:is_admin]
    respond_to do |format|
      format.html { redirect_to instruments_url }
      format.json { head :no_content }
    end  # do
  end  # destroy

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instrument
      @instrument = Instrument.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instrument_params
      params.require(:instrument).permit(:instrument_type_id, :instrument_name, :instrument_model, :datafile)
    end
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/views/instruments/_form.html.erb
<%= form_for(@instrument, :html => {:multipart=>true}) do |f| %>
  <% if @instrument.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instrument.errors.count, "error") %> prohibited this instrument from being saved:</h2>

      <ul>
      <% @instrument.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <thead></thead>
    <tbody>
      <tr>
  <div class="field">
    <td><%= f.label :instrument_type_id %></td>
    <td><%= f.collection_select(:instrument_type_id, @instrument_types, :id, :category) %></td>
  </div>
      </tr><tr>
  <div class="field">
    <td><%= f.label :instrument_name %></td>
    <td><%= f.text_field :instrument_name, :size => 40 %></td>
  </div>
      </tr><tr>
  <div class="field">
    <td><%= f.label :instrument_model %></td>
    <td><%= f.text_field :instrument_model, :size => 40 %></td>
  </div>
      </tr><tr>
  <div class="field">
    <td><%= f.label :image %></td>
    <td><%= f.file_field("datafile") %></td>
  </div>
      </tr>
    </tbody>
  </table>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/instruments/edit.html.erb
<h1>Editing instrument</h1>

<%= render 'form' %>

<%= link_to 'Show', @instrument %> |
<%= link_to 'Back', instruments_path %>

app/views/instruments/index.html.erb
<h1>Instruments</h1>

<table cellpadding="2" border="0" class="display dataTable" id="example">
  <thead>
    <tr>
      <th>Instrument type</th>
      <th>Instrument name</th>
      <th>Instrument model</th>
      <th>Thumbnail</th>
      <th></th>
      <% if session[:is_admin] -%>
        <th></th>
        <th></th>
      <% end -%>
    </tr>
  </thead>

  <tbody>
    <% @instruments.each do |instrument| -%>
      <tr>
        <td><%= @instrument_types_hash[instrument.instrument_type_id].category if ! @instrument_types_hash[instrument.instrument_type_id].nil?  %></td>
        <td><%= instrument.instrument_name %></td>
        <td><%= instrument.instrument_model %></td>
        <td><%= image_tag(url_for(:controller => :images, :action => :show_img, :id => instrument.image_id), :ISMAP => 'false', :border => '0', :height => '100', :width => '100') if ! instrument.image_id.nil? %></td>
        <td><%= link_to 'Show', instrument %></td>
        <% if session[:is_admin] -%>
          <td><%= link_to 'Edit', edit_instrument_path(instrument) %></td>
          <td><%= link_to 'Destroy', instrument, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end -%>
      </tr>
    <% end -%>
  </tbody>
</table>

<br>

<%= link_to 'New Instrument', new_instrument_path if (! session[:user_id].nil?) %>

app/views/instruments/new.html.erb
<h1>New instrument</h1>

<%= render 'form' %>

<%= link_to 'Back', instruments_path %>

app/views/instruments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Instrument type:</strong>
  <%= @instrument_types_hash[@instrument.instrument_type_id].category if ! @instrument.instrument_type_id.nil? %>
</p>

<p>
  <strong>Instrument name:</strong>
  <%= @instrument.instrument_name %>
</p>

<p>
  <strong>Instrument model:</strong>
  <%= @instrument.instrument_model %>
</p>

<p>
  <%= link_to image_tag(url_for(:controller => :images, :action => :show_img, :id => @instrument.image_id)) if ! @instrument.image_id.nil? %>
</p>

<% if @owns || session[:is_admin] -%>
  <%= link_to 'Edit', edit_instrument_path(@instrument) %> |
<% end -%>
<%= link_to 'Back', instruments_path %>